#!/usr/bin/env bash
# This script displays numbers from 1 to 100 in a list format:
# Displays FizzBuzz when the number is a multiple of 3 and 5
# Displays Fizz when the number is multiple of 3
# Displays Buzz when the number is a multiple of 5
# Otherwise, displays the number

i=1
while [[ i -le 100 ]];
do
	if (( i % 3 == 0 & i % 5 == 0 ))
	then
		echo "FizzBuzz"
		((i+=1))
	elif (( i % 3 == 0 ));
	then
		echo "Fizz"
		((i+=1))
	elif (( i % 5 == 0 ));
	then
		echo "Buzz"
		((i+=1))
	else
		echo "$i"
		((i+=1))
	fi
done
