#!/usr/bin/env bash
# This script displays "Best School" 10 times using while loop

i=0
while [[ i -lt 10 ]];
do
	if [[ i -eq 3 ]]
	then
		echo "bad luck"
		((i+=1))
	elif [[ i -eq 7 ]];
	then
		echo "good luck"
		((i+=1))
	else
		echo "Best School"
		((i+=1))
	fi
done
