#!/usr/bin/env bash
# This script displays "Best School" 10 times using while loop

i=1
while [[ $i -le 20 ]];
do
	echo $i
	((i+=1))
	case $i in
		5)
			echo "bad luck from China"
			;;
		10)
			echo "bad luck from Japan"
			;;
		18)
			echo "bad luck from Italy"
			;;
	esac
done
